### ISSUE TITLE
ABI issue for WriterSSE2

### ISSUE THREAD

**Issue by gauthier-voron** [fgaud/Minime#1]
Corrupted registers r12 and r13

The UNIX ABI require that registers r12 and r13 belongs to the calling function.
The WriterSSE2 routine modify these registers without saving them on stack.
This could lead to unpredictable behavior.

**Comment by BLepers** [comment]
Should be fixed by 71de4b82e199935021e74fde31b972c63686ed83 ; thanks for the bug report.
